### ISSUE TITLE
[BUG] 1.20.1,Request adaptation

### ISSUE THREAD

**Issue by welove69** [PotatoCraft-Studio/QuickShop-Reremake#362] opened 2023-06-15 20:27 UTC
### Description

Request adaptation,1.20.1

### Steps to reproduce

1.20.1,Unusable

### Expected Behaviour

Request adaptation,1.20.1

### Screenshots

WARN

### `/qs paste` URL

WARN

**Comment by sandtechnology** [comment] 2023-06-16 14:21
Close this issue due to is not a bug and you can just use snapshot, it should support 1.20 now: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/

**Closed by sandtechnology** 2023-06-16 14:21 UTC
